inline_height = 20
enter_accept = true
keymap_mode = "vim-normal"

[stats]
## Set commands where we should consider the subcommand for statistics. Eg, kubectl get vs just kubectl
common_subcommands = [
  "apt",
  "cargo",
  "composer",
  "conda",
  "dnf",
  "docker",
  "dotnet",
  "git",
  "go",
  "ip",
  "jj",
  "kubectl",
  "micromamba",
  "nix",
  "nmcli",
  "npm",
  "pecl",
  "pnpm",
  "podman",
  "port",
  "systemctl",
  "tmux",
  "uv",
  "yarn",
]

## Set commands that should be totally stripped and ignored from stats
common_prefix = ["sudo"]

## Set commands that will be completely ignored from stats
ignored_commands = ["cd", "ls", "nvim", "vi", "vim"]

[sync]
records = true

[theme]
name = "gruvbox-dark"

[tmux]
enabled = true
