inline_height = 20
enter_accept = true
keymap_mode = "vim-normal"

[stats]
## Include the subcommand in statistics for these commands.
common_subcommands = [
  "apt",
  "cargo",
  "composer",
  "conda",
  "dnf",
  "docker",
  "dotnet",
  "git",
  "go",
  "ip",
  "jj",
  "kubectl",
  "micromamba",
  "mise",
  "nix",
  "nmcli",
  "npm",
  "pecl",
  "pipx",
  "pnpm",
  "podman",
  "port",
  "systemctl",
  "tmux",
  "uv",
  "yarn",
  "zellij",
]

## Strip these prefixes from statistics.
common_prefix = ["sudo"]

## Ignore these commands in statistics.
ignored_commands = ["cd", "ls", "nvim", "vi", "vim"]

[sync]
records = true

[theme]
name = "gruvbox-dark"

[tmux]
enabled = true
