[".vim/pack/plugins/start/fugitive"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-fugitive.git"
  refreshPeriod = "168h"
[".vim/pack/plugins/start/gruvbox"]
  type = "git-repo"
  url = "https://github.com/morhetz/gruvbox.git"
  refreshPeriod = "168h"
[".vim/pack/plugins/start/surround"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-surround.git"
  refreshPeriod = "168h"
[".vim/pack/plugins/start/nord"]
  type = "git-repo"
  url = "https://github.com/nordtheme/vim.git"
  refreshPeriod = "168h"
[".vim/pack/plugins/start/lightline"]
  type = "git-repo"
  url = "https://github.com/itchyny/lightline.vim.git"
  refreshPeriod = "168h"
[".vim/pack/plugins/start/nerdtree"]
  type = "git-repo"
  url = "https://github.com/preservim/nerdtree.git"
  refreshPeriod = "168h"
[".vim/pack/plugins/start/nerdcommenter"]
  type = "git-repo"
  url = "https://github.com/preservim/nerdcommenter.git"
  refreshPeriod = "168h"
[".tmux/plugins/tpm"]
  type = "git-repo"
  url = "https://github.com/tmux-plugins/tpm"
  refreshPeriod = "168h"
