[".vim/pack/plugins/start/gruvbox"]
  type = "git-repo"
  url = "https://github.com/morhetz/gruvbox.git"
  refreshPeriod = "168h"
[".vim/pack/plugins/start/lightline"]
  type = "git-repo"
  url = "https://github.com/itchyny/lightline.vim.git"
  refreshPeriod = "168h"
[".vim/pack/plugins/start/nerdtree"]
  type = "git-repo"
  url = "https://github.com/preservim/nerdtree.git"
  refreshPeriod = "168h"
[".vim/pack/plugins/start/nerdcommenter"]
  type = "git-repo"
  url = "https://github.com/preservim/nerdcommenter.git"
  refreshPeriod = "168h"
[".local/share/nvim/site/pack/packer/start/packer.nvim"]
  type="git-repo"
  url = "https://github.com/wbthomason/packer.nvim"
  refreshPeriod = "168h"

